CREATE DATABASE empre_1e;
USE empre_1e;

CREATE TABLE DEPARTAMENTO(
DEPCODIGO INTEGER PRIMARY KEY,
DEPNOME VARCHAR(50)
);

CREATE TABLE FUNCIONARIO(
FUNCODIGO INTEGER PRIMARY KEY,
DEPCODIGO INTEGER,
FUNNOME VARCHAR(50),
FUNNASCIMENTO DATE,
FUNSALARIO NUMERIC(10,2),
FOREIGN KEY(DEPCODIGO) REFERENCES DEPARTAMENTO(DEPCODIGO)
);

CREATE TABLE DEPENDENTE(
DEPENCODIGO INTEGER PRIMARY KEY,
FUNCODIGO INTEGER,
DEPENNOME VARCHAR(100),
FOREIGN KEY(FUNCODIGO) REFERENCES FUNCIONARIO(FUNCODIGO)
);